# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "tailwindcss-4.1.13" = {
      name = "tailwindcss";
      packageName = "tailwindcss";
      version = "4.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/tailwindcss/-/tailwindcss-4.1.13.tgz";
        sha512 = "i+zidfmTqtwquj4hMEwdjshYYgMbOrPzb9a0M3ZgNa0JMoZeFC6bxZvO8yr8ozS6ix2SDz0+mvryPeBs2TFE+w==";
      };
    };
  };
  args = {
    name = "styles";
    packageName = "styles";
    version = "0.0.0";
    src = ./.;
    dependencies = [
      sources."tailwindcss-4.1.13"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = false;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
